import { slugify } from "../lib/slugify.js";

function placeholder(label) {
  return `https://placehold.co/480x720/f8f4ee/5b4330/png?text=${encodeURIComponent(label)}`;
}

function codeFromText(value) {
  const parts = slugify(value)
    .split("-")
    .filter(Boolean);
  if (!parts.length) return "VAR";
  return parts
    .map((part) => part[0])
    .join("")
    .toUpperCase()
    .slice(0, 3)
    .padEnd(3, "X");
}

const CATEGORY_BLUEPRINTS = [
  {
    name: "Banarasi Sarees",
    slug: "banarasi-sarees",
    code: "BAR",
    description: "Rich festive Banarasi weaves with statement zari work.",
    products: [
      {
        name: "Royal Emerald Banarasi",
        color: "Emerald Green",
        material: "Banarasi Silk",
        price: 4999,
        stock: 8,
        detail: "Rich zari borders with a luminous finish",
        occasion: "weddings and festive evenings",
      },
      {
        name: "Ruby Banarasi Zari",
        color: "Ruby Red",
        material: "Pure Silk Banarasi",
        price: 5499,
        stock: 7,
        detail: "Dense zari motifs with a polished sheen",
        occasion: "receptions and temple visits",
      },
      {
        name: "Ivory Banarasi Glow",
        color: "Ivory",
        material: "Banarasi Silk",
        price: 6999,
        stock: 6,
        detail: "Soft ivory base with a gold pallu",
        occasion: "day ceremonies and gifting",
      },
      {
        name: "Midnight Banarasi Regal",
        color: "Midnight Blue",
        material: "Banarasi Silk",
        price: 8499,
        stock: 5,
        detail: "Deep tone with ornate border detailing",
        occasion: "evening functions and photoshoots",
      },
      {
        name: "Saffron Banarasi Heritage",
        color: "Saffron",
        material: "Handloom Silk",
        price: 10999,
        stock: 4,
        detail: "Heritage weave with a bold festive palette",
        occasion: "marriages and grand celebrations",
      },
    ],
  },
  {
    name: "Cotton Sarees",
    slug: "cotton-sarees",
    code: "COT",
    description: "Breathable everyday cotton sarees with easy styling.",
    products: [
      {
        name: "Sky Cotton Everyday",
        color: "Sky Blue",
        material: "Cotton",
        price: 699,
        stock: 18,
        detail: "Breathable weave with a clean everyday drape",
        occasion: "daily wear and errands",
      },
      {
        name: "Ivory Cotton Border",
        color: "Ivory",
        material: "Handloom Cotton",
        price: 899,
        stock: 16,
        detail: "Minimal border work with an airy texture",
        occasion: "office days and casual outings",
      },
      {
        name: "Rose Cotton Check",
        color: "Rose Pink",
        material: "Cotton",
        price: 1199,
        stock: 15,
        detail: "Classic checks with a soft hand-feel",
        occasion: "lunches and relaxed weekends",
      },
      {
        name: "Sage Cotton Weave",
        color: "Sage Green",
        material: "Cotton",
        price: 1499,
        stock: 14,
        detail: "Balanced weave with a polished finish",
        occasion: "workwear and travel",
      },
      {
        name: "Mustard Cotton Handloom",
        color: "Mustard",
        material: "Handloom Cotton",
        price: 1899,
        stock: 12,
        detail: "Handloom character with a strong color pop",
        occasion: "day functions and gifting",
      },
    ],
  },
  {
    name: "Silk Sarees",
    slug: "silk-sarees",
    code: "SLK",
    description: "Smooth silk sarees with elegant drape and sheen.",
    products: [
      {
        name: "Purple Silk Grace",
        color: "Purple",
        material: "Pure Silk",
        price: 2999,
        stock: 10,
        detail: "Smooth sheen with a light festive border",
        occasion: "small celebrations and family dinners",
      },
      {
        name: "Maroon Silk Regal",
        color: "Maroon",
        material: "Pure Silk",
        price: 3499,
        stock: 9,
        detail: "Rich tone with a graceful drape",
        occasion: "weddings and pooja events",
      },
      {
        name: "Navy Silk Statement",
        color: "Navy Blue",
        material: "Pure Silk",
        price: 3999,
        stock: 8,
        detail: "Deep shade with a refined finish",
        occasion: "formal evenings and receptions",
      },
      {
        name: "Emerald Silk Shine",
        color: "Emerald Green",
        material: "Silk",
        price: 4999,
        stock: 7,
        detail: "Vivid body with elegant zari cues",
        occasion: "festival wear and parties",
      },
      {
        name: "Gold Silk Classic",
        color: "Gold",
        material: "Silk",
        price: 6999,
        stock: 6,
        detail: "Timeless gold tone with a premium fall",
        occasion: "grand celebrations and gifts",
      },
    ],
  },
  {
    name: "Printed Sarees",
    slug: "printed-sarees",
    code: "PRT",
    description: "Light printed sarees for casual and workday dressing.",
    products: [
      {
        name: "Floral Print Casual",
        color: "Multi-color",
        material: "Cotton Blend",
        price: 899,
        stock: 20,
        detail: "Bright floral print with a soft drape",
        occasion: "casual wear and summer days",
      },
      {
        name: "Geometric Print Modern",
        color: "Multi-color",
        material: "Cotton Blend",
        price: 1099,
        stock: 18,
        detail: "Clean lines and contemporary contrast",
        occasion: "work-from-home and lunch plans",
      },
      {
        name: "Paisley Print Breeze",
        color: "Multi-color",
        material: "Viscose Blend",
        price: 1399,
        stock: 16,
        detail: "Light paisley movement with easy wear",
        occasion: "daily styling and travel",
      },
      {
        name: "Abstract Print Vibrant",
        color: "Multi-color",
        material: "Rayon Blend",
        price: 1699,
        stock: 14,
        detail: "Artful prints with a lively palette",
        occasion: "weekend outings and events",
      },
      {
        name: "Block Print Daywear",
        color: "Indigo",
        material: "Cotton Blend",
        price: 2099,
        stock: 12,
        detail: "Traditional block print with practical comfort",
        occasion: "market visits and office casual",
      },
    ],
  },
  {
    name: "Designer Sarees",
    slug: "designer-sarees",
    code: "DES",
    description: "Premium designer sarees for standout occasions.",
    products: [
      {
        name: "Designer Festive Gold",
        color: "Gold",
        material: "Silk with Embroidery",
        price: 5999,
        stock: 6,
        detail: "Embroidered finish with celebration sparkle",
        occasion: "festivals and family occasions",
      },
      {
        name: "Designer Bridal Pearl",
        color: "Pearl White",
        material: "Silk with Stones",
        price: 7499,
        stock: 5,
        detail: "Pearl tone with delicate stone accents",
        occasion: "bridal events and engagements",
      },
      {
        name: "Designer Party Emerald",
        color: "Emerald",
        material: "Organza Blend",
        price: 8999,
        stock: 5,
        detail: "Modern styling with statement edge",
        occasion: "party nights and receptions",
      },
      {
        name: "Designer Celebration Rose",
        color: "Rose",
        material: "Satin Blend",
        price: 11999,
        stock: 4,
        detail: "Soft rose body with layered detailing",
        occasion: "sangeet and premium gatherings",
      },
      {
        name: "Designer Evening Noir",
        color: "Black",
        material: "Velvet Blend",
        price: 14999,
        stock: 3,
        detail: "Bold contrast with a couture feel",
        occasion: "high-profile events and editorials",
      },
    ],
  },
  {
    name: "Kanjivaram Sarees",
    slug: "kanjivaram-sarees",
    code: "KAN",
    description: "Traditional Kanjivaram sarees with temple-inspired borders.",
    products: [
      {
        name: "Temple Gold Kanjivaram",
        color: "Antique Gold",
        material: "Kanjivaram Silk",
        price: 6999,
        stock: 7,
        detail: "Temple border with strong festive energy",
        occasion: "traditional ceremonies and weddings",
      },
      {
        name: "Royal Maroon Kanjivaram",
        color: "Maroon",
        material: "Kanjivaram Silk",
        price: 8499,
        stock: 6,
        detail: "Classic maroon body with rich contrast",
        occasion: "religious functions and receptions",
      },
      {
        name: "Lotus Green Kanjivaram",
        color: "Lotus Green",
        material: "Kanjivaram Silk",
        price: 9999,
        stock: 5,
        detail: "Vibrant green with a woven border story",
        occasion: "family celebrations and gifting",
      },
      {
        name: "Bridal Red Kanjivaram",
        color: "Bridal Red",
        material: "Kanjivaram Silk",
        price: 12999,
        stock: 4,
        detail: "Bridal-ready tone with heavy weave presence",
        occasion: "weddings and muhurtham looks",
      },
      {
        name: "Heritage Navy Kanjivaram",
        color: "Navy Blue",
        material: "Kanjivaram Silk",
        price: 15999,
        stock: 3,
        detail: "Deep heritage hue with a premium drape",
        occasion: "grand ceremonies and heirloom wear",
      },
    ],
  },
  {
    name: "Chiffon Sarees",
    slug: "chiffon-sarees",
    code: "CHF",
    description: "Airy chiffon sarees with a graceful floating feel.",
    products: [
      {
        name: "Coral Chiffon Flow",
        color: "Coral",
        material: "Chiffon",
        price: 1299,
        stock: 18,
        detail: "Light chiffon with a soft floating drape",
        occasion: "day wear and travel",
      },
      {
        name: "Lavender Chiffon Grace",
        color: "Lavender",
        material: "Chiffon",
        price: 1599,
        stock: 16,
        detail: "Airy finish with a gentle pastel tone",
        occasion: "brunches and casual celebrations",
      },
      {
        name: "Peach Chiffon Drift",
        color: "Peach",
        material: "Chiffon",
        price: 1899,
        stock: 15,
        detail: "Easy movement and bright seasonal color",
        occasion: "summer outings and dinners",
      },
      {
        name: "Ivory Chiffon Breeze",
        color: "Ivory",
        material: "Chiffon",
        price: 2299,
        stock: 12,
        detail: "Clean neutral tone with a fluid silhouette",
        occasion: "office events and lightweight styling",
      },
      {
        name: "Blue Chiffon Drape",
        color: "Blue",
        material: "Chiffon",
        price: 2799,
        stock: 10,
        detail: "Cool blue shade with a polished fall",
        occasion: "evening wear and gifting",
      },
    ],
  },
  {
    name: "Georgette Sarees",
    slug: "georgette-sarees",
    code: "GGT",
    description: "Soft georgette sarees with fluid movement and comfort.",
    products: [
      {
        name: "Plum Georgette Drape",
        color: "Plum",
        material: "Georgette",
        price: 1699,
        stock: 16,
        detail: "Soft georgette with a graceful fall",
        occasion: "daily wear and short outings",
      },
      {
        name: "Mint Georgette Swirl",
        color: "Mint Green",
        material: "Georgette",
        price: 1999,
        stock: 14,
        detail: "Fresh color with an easy flow",
        occasion: "day events and travel",
      },
      {
        name: "Ruby Georgette Flow",
        color: "Ruby Red",
        material: "Georgette",
        price: 2499,
        stock: 12,
        detail: "Balanced body with a standout tone",
        occasion: "dinners and festive meets",
      },
      {
        name: "Sage Georgette Breeze",
        color: "Sage Green",
        material: "Georgette",
        price: 2999,
        stock: 10,
        detail: "Muted palette with a soft wearable texture",
        occasion: "office wear and functions",
      },
      {
        name: "Charcoal Georgette Grace",
        color: "Charcoal",
        material: "Georgette",
        price: 3699,
        stock: 8,
        detail: "Modern dark tone with subtle shine",
        occasion: "evening gatherings and parties",
      },
    ],
  },
  {
    name: "Linen Sarees",
    slug: "linen-sarees",
    code: "LIN",
    description: "Breathable linen sarees with crisp everyday character.",
    products: [
      {
        name: "Sand Linen Ease",
        color: "Sand",
        material: "Linen",
        price: 1499,
        stock: 15,
        detail: "Cool linen with a crisp everyday feel",
        occasion: "summer wear and errands",
      },
      {
        name: "Olive Linen Calm",
        color: "Olive Green",
        material: "Linen",
        price: 1799,
        stock: 13,
        detail: "Earthy shade with a breathable hand",
        occasion: "workwear and weekend plans",
      },
      {
        name: "Indigo Linen Office",
        color: "Indigo",
        material: "Linen",
        price: 2199,
        stock: 11,
        detail: "Smart color with a tailored look",
        occasion: "office days and meetings",
      },
      {
        name: "Beige Linen Border",
        color: "Beige",
        material: "Linen",
        price: 2599,
        stock: 9,
        detail: "Clean border styling with a polished base",
        occasion: "luncheons and day functions",
      },
      {
        name: "Rust Linen Handloom",
        color: "Rust",
        material: "Handloom Linen",
        price: 3199,
        stock: 8,
        detail: "Textured finish with handcrafted character",
        occasion: "gifts and refined casual wear",
      },
    ],
  },
  {
    name: "Organza Sarees",
    slug: "organza-sarees",
    code: "ORG",
    description: "Sheer organza sarees with a polished contemporary finish.",
    products: [
      {
        name: "Pink Organza Bloom",
        color: "Pink",
        material: "Organza",
        price: 2499,
        stock: 14,
        detail: "Sheer organza with a floral mood",
        occasion: "day celebrations and festive visits",
      },
      {
        name: "Ivory Organza Sheen",
        color: "Ivory",
        material: "Organza",
        price: 2999,
        stock: 12,
        detail: "Light shimmer with a clean premium look",
        occasion: "engagements and elegant dressing",
      },
      {
        name: "Gold Organza Mist",
        color: "Gold",
        material: "Organza",
        price: 3599,
        stock: 10,
        detail: "Subtle shine with an airy fall",
        occasion: "receptions and celebrations",
      },
      {
        name: "Lilac Organza Air",
        color: "Lilac",
        material: "Organza",
        price: 4499,
        stock: 8,
        detail: "Soft lilac tone with standout lightness",
        occasion: "party styling and gifting",
      },
      {
        name: "Silver Organza Whisper",
        color: "Silver",
        material: "Organza",
        price: 5799,
        stock: 6,
        detail: "Delicate silver finish with occasion polish",
        occasion: "premium events and photoshoots",
      },
    ],
  },
];

export function buildSeedCatalog() {
  const categories = CATEGORY_BLUEPRINTS.map(({ code, products, ...category }) => category);
  const products = CATEGORY_BLUEPRINTS.flatMap((category) =>
    category.products.map((variant, index) => {
      const slug = slugify(variant.name);
      const tagSuffix = codeFromText(variant.name);
      const skuSuffix = codeFromText(variant.color || variant.name);

      return {
        name: variant.name,
        slug,
        tagId: `${category.code}-${String(index + 1).padStart(3, "0")}-${tagSuffix}`,
        description: `${variant.detail} for ${variant.occasion}.`,
        price: variant.price,
        categorySlug: category.slug,
        images: [placeholder(variant.imageLabel || variant.name)],
        stock: variant.stock,
        color: variant.color,
        material: variant.material,
        size: variant.size ?? "5.5m",
        sku: `${category.code}-${String(index + 1).padStart(3, "0")}-${skuSuffix}`,
        isActive: true,
      };
    })
  );

  return { categories, products };
}
